## 따라하기

In [6]:
import pandas as pd

In [11]:
#pd.read_csv("zigbang.csv")
df = pd.read_csv("../안수찬_강의실습/zigbang.csv")
#.. 이전폴더 . 현재폴더
df

                                     address     phonenumber  deposit  rent
0              서울특별시 구로구 가마산로 286 101호 (구로동)  0507-1280-2016     5500     0
1                             충남 당진시 읍내동 985   010-2910-4300     2000    50
2                                        NaN   010-4705-6713      300    30
3                        서울특별시 구로구 구로동 97-17     02-864-6666     1000    45
4    경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858     2000    35
5                      부산광역시 부산진구 전포동 309-50  0507-1280-8473      300    26
6                        서울특별시 구로구 구로동 97-17     02-864-6666    10000     0
7                                        NaN   010-9327-2443      500    35
8                   서울특별시 관악구 봉천동 1611-23 1층  0507-1280-1758      200    41
9    경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      300    55
10                       서울특별시 성동구 도선동 285-1    02-2295-2295     8000     0
11                     부산시 부산진구 전포동 661-1 1층   010-5050-3777    11000     0
12                  서울특별시 관악구 봉천동 1611-23 1층  0507-1280-1758      100    37
13         서울특별시 종로구 숭인동 201-11 유케이오피스텔 101호  0507-1280-6783     6000     0
14   경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858     1000    50
15                       서울특별시 강남구 봉은사로33길14   010-4734-5665     1000   130
16           서울특별시 성북구 동소문로 23길 34 (동선동5가38)  0507-1280-0913     5000    50
17                         서울특별시 광진구 능동로 147   010-8503-7100     7500     0
18   경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      500    50
19               경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      200    27
20  경기도 부천시 원미구 상3동 531-3번지 광장프라자 106호 광장부동산   010-9169-9399     2000    25
21                            충남 당진시 읍내동 985   010-2910-4300      300    28
22                   서울특별시 동대문구 이문로 40 (휘경동)  0507-1280-1411      500    40
23            서울특별시 광진구 아차산로 25길 7, 1층 (화양동)  0507-1280-4998     1000    45
24               서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     2000    70
25               서울 강남구 강남대로84길 15, 111(역삼동)   010-3757-9850     1000    85
26            서울특별시 마포구 노고산동 31-157번지 에버빌딩2층  0507-1280-1672     8000     0
27               서울특별시 구로구 구로동 103-11 한솔로이젠트   010-2482-5292     3000    40
28                서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305     5000    33
29   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
..                                       ...             ...      ...   ...
43                서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305      500    55
44                      서울특별시 중랑구 면목동 105-29  0507-1280-8071      500    40
45                         서울시 강남구 삼성로63길 15   010-4187-0222     1000    50
46            서울특별시 관악구 봉천동 875-1 관악캠퍼스타워 1층  0507-1280-7645     5000    10
47                  서울특별시 관악구 봉천동 1611-23 1층  0507-1280-1758      100    39
48               경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      200    27
49              서울특별시 강남구 테헤란로22길 72 1층(역삼동)  0507-1280-4100     6000    30
50                     서울특별시 강서구 화곡동 342-100  0507-1280-5503     4000     0
51                       서울특별시 관악구 봉천동1665-7  0507-1280-8679    14000     0
52                     부산시 부산진구 전포동 661-1 1층   010-5050-3777     7500     0
53            서울특별시 마포구 월드컵로36길14두산위브센티움412호  0507-1280-3984     2000    80
54                  서울특별시 관악구 봉천동 1611-23 1층  0507-1280-0478     1000    35
55                     부산광역시 부산진구 전포동 309-50  0507-1280-7705    18000     0
56               서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     5000   105
57                       서울특별시 중랑구 묵동 177-28  0507-1280-6032    13000     0
58                      서울특별시 중랑구 면목동 105-29  0507-1280-8071      500    45
59                    서울특별시 관악구 남부순환로230길 12  0108-2216-8421      100    44
60               경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      500    55
61   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265      100    90
62                                       NaN   010-4667-7617     7500     0
63              서울특별시 강남구 봉은사로61길 30 1층(삼성동)   010-4019-0430     1000    70
64                      서울특별시 중랑구 면목동 105-29  0507-1280-8071      500    40
65                    서울특별시 관악구 남부순환로230길 12  0108-2216-8421      100    34
66                                화곡동 343-57   010-5180-1559       60    55
67       부산시 수영구 광안3동 1069-3 동일아파트상가 108-102   010-3922-4689      500    33
68   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
69                    서울특별시 관악구 남부순환로230길 12  0108-2216-8421      300    40
70        경기도 안양시 만안구 안양2동 815-7 한양하이츠빌 102호  0507-1280-8080     1000    45
71                     서울특별시 강남구 역삼동 672-2번지  0507-1280-1797      100   100
72                            충남 당진시 읍내동 985   010-2910-4300      700    43

[73 rows x 4 columns]

### 이게 어제 과제1의 답안임
* pandas로 db에 저장시 덮어쓰기 때문에 위험
* 직접 db에서 테이블을 만들고 그 형식에 맞춰 집어넣어야함

In [13]:
for index, row in df.iterrows():
    address = row.get("address")
    # address = row("address")
    phonenumber = row.get("phonenumber")
    deposit = row.get("deposit")
    rent = row.get("rent")
    
    SQL_QUERY = """
        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            '{address}',
            '{phonenumber}',
            '{deposit}',
            '{rent}'
            )
            ;
        """.format(
                address=address,
                phonenumber=phonenumber,
                deposit=deposit,
                rent=rent,
        )
    
    print(SQL_QUERY)

        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 구로구 가마산로 286 101호 (구로동),
            0507-1280-2016,
            5500.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            충남 당진시 읍내동 985,
            010-2910-4300,
            2000.0,
            50.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            nan,
            010-4705-6713,
            300.0,
            30.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 구로구 구로동 97-17,
            02-864-6666,
            1000.0,
            45.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호,
            0507-1280-0858,
            2000.0,
            35.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            부산광역시 부산진구 전포동 309-50,
            0507-1280-8473,
            300.0,
            26.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 구로구 구로동 97-17,
            02-864-6666,
            10000.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            nan,
            010-9327-2443,
            500.0,
            35.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 봉천동 1611-23 1층,
            0507-1280-1758,
            200.0,
            41.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호,
            0507-1280-0858,
            300.0,
            55.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 성동구 도선동 285-1,
            02-2295-2295,
            8000.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            부산시 부산진구 전포동 661-1 1층,
            010-5050-3777,
            11000.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 봉천동 1611-23 1층,
            0507-1280-1758,
            100.0,
            37.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 종로구 숭인동 201-11 유케이오피스텔 101호,
            0507-1280-6783,
            6000.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호,
            0507-1280-0858,
            1000.0,
            50.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 강남구 봉은사로33길14,
            010-4734-5665,
            1000.0,
            130.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 성북구 동소문로 23길 34 (동선동5가38),
            0507-1280-0913,
            5000.0,
            50.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 광진구 능동로 147,
            010-8503-7100,
            7500.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호,
            0507-1280-0858,
            500.0,
            50.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경북 구미시 형곡동 168-4번지 대림베스트빌2차,
            0000-0000-0000,
            200.0,
            27.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경기도 부천시 원미구 상3동 531-3번지 광장프라자 106호 광장부동산,
            010-9169-9399,
            2000.0,
            25.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            충남 당진시 읍내동 985,
            010-2910-4300,
            300.0,
            28.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 동대문구 이문로 40 (휘경동),
            0507-1280-1411,
            500.0,
            40.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 광진구 아차산로 25길 7, 1층 (화양동),
            0507-1280-4998,
            1000.0,
            45.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 강남구 논현로76길 14 1층(역삼동),
            0507-1280-3843,
            2000.0,
            70.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울 강남구 강남대로84길 15, 111(역삼동),
            010-3757-9850,
            1000.0,
            85.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 마포구 노고산동 31-157번지 에버빌딩2층,
            0507-1280-1672,
            8000.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 구로구 구로동 103-11 한솔로이젠트,
            010-2482-5292,
            3000.0,
            40.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 마포구 도화동 4-48(새창로 34),
            0507-1280-7305,
            5000.0,
            33.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호,
            010-9790-4265,
            60.0,
            60.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 성동구 도선동 285-1,
            02-2295-2295,
            6500.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            인천광역시 부평구 부평동 539-2 현대더로프트 101동144호,
            010-4943-8897,
            300.0,
            42.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            충남 당진시 읍내동 985,
            010-2910-4300,
            500.0,
            39.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 봉천동 1611-23 1층,
            0507-1280-1758,
            100.0,
            39.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 구로구 구로동 103-11 한솔로이젠트,
            010-2482-5292,
            1000.0,
            70.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 은평구 통일로69길 33 (대조동),
            0507-1280-2193,
            2000.0,
            60.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 광진구 아차산로 25길 7, 1층 (화양동),
            0507-1280-4998,
            2500.0,
            35.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호,
            010-9790-4265,
            1000.0,
            90.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 광진구 자양로13길 60,
            0507-1280-5505,
            11000.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 은평구 통일로69길 33 (대조동),
            0507-1280-2193,
            2000.0,
            60.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 구로구 구로동 103-11 한솔로이젠트,
            010-2482-5292,
            5000.0,
            35.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 봉천동 1611-23 1층,
            0507-1280-1758,
            100.0,
            39.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            인천광역시 부평구 부평동 539-2 현대더로프트 101동144호,
            010-4943-8897,
            50.0,
            45.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 마포구 도화동 4-48(새창로 34),
            0507-1280-7305,
            500.0,
            55.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 중랑구 면목동 105-29,
            0507-1280-8071,
            500.0,
            40.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울시 강남구 삼성로63길 15,
            010-4187-0222,
            1000.0,
            50.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 봉천동 875-1 관악캠퍼스타워 1층,
            0507-1280-7645,
            5000.0,
            10.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 봉천동 1611-23 1층,
            0507-1280-1758,
            100.0,
            39.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경북 구미시 형곡동 168-4번지 대림베스트빌2차,
            0000-0000-0000,
            200.0,
            27.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 강남구 테헤란로22길 72 1층(역삼동),
            0507-1280-4100,
            6000.0,
            30.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 강서구 화곡동 342-100,
            0507-1280-5503,
            4000.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 봉천동1665-7,
            0507-1280-8679,
            14000.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            부산시 부산진구 전포동 661-1 1층,
            010-5050-3777,
            7500.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 마포구 월드컵로36길14두산위브센티움412호,
            0507-1280-3984,
            2000.0,
            80.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 봉천동 1611-23 1층,
            0507-1280-0478,
            1000.0,
            35.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            부산광역시 부산진구 전포동 309-50,
            0507-1280-7705,
            18000.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 강남구 논현로76길 14 1층(역삼동),
            0507-1280-3843,
            5000.0,
            105.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 중랑구 묵동 177-28,
            0507-1280-6032,
            13000.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 중랑구 면목동 105-29,
            0507-1280-8071,
            500.0,
            45.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 남부순환로230길 12,
            0108-2216-8421,
            100.0,
            44.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경북 구미시 형곡동 168-4번지 대림베스트빌2차,
            0000-0000-0000,
            500.0,
            55.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호,
            010-9790-4265,
            100.0,
            90.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            nan,
            010-4667-7617,
            7500.0,
            0.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 강남구 봉은사로61길 30 1층(삼성동),
            010-4019-0430,
            1000.0,
            70.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 중랑구 면목동 105-29,
            0507-1280-8071,
            500.0,
            40.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 남부순환로230길 12,
            0108-2216-8421,
            100.0,
            34.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            화곡동 343-57,
            010-5180-1559,
            60.0,
            55.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            부산시 수영구 광안3동 1069-3 동일아파트상가 108-102,
            010-3922-4689,
            500.0,
            33.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호,
            010-9790-4265,
            60.0,
            60.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 관악구 남부순환로230길 12,
            0108-2216-8421,
            300.0,
            40.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            경기도 안양시 만안구 안양2동 815-7 한양하이츠빌 102호,
            0507-1280-8080,
            1000.0,
            45.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            서울특별시 강남구 역삼동 672-2번지,
            0507-1280-1797,
            100.0,
            100.0
            )
            ;


        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            충남 당진시 읍내동 985,
            010-2910-4300,
            700.0,
            43.0
            )
            ;

### 시퀄프로 들어가서 db 생성

In [18]:
import MySQLdb

db = MySQLdb.connect(
    "db.fastcamp.us",
    "root",
    "dkstncks",
    "jkeun_sample",
    charset='utf8',
)

cursor = db.cursor()

In [20]:
for index, row in df.iterrows():
    address = row.get("address")
    # address = row("address")
    phonenumber = row.get("phonenumber")
    deposit = row.get("deposit")
    rent = row.get("rent")
    
    SQL_QUERY = """
        INSERT INTO zigbang (address, phonenumber, deposit, rent)
        VALUES (
            '{address}',
            '{phonenumber}',
            '{deposit}',
            '{rent}'
            )
            ;
        """.format(
                address=address,
                phonenumber=phonenumber,
                deposit=deposit,
                rent=rent,
        )
    
    
    cursor.execute(SQL_QUERY)
    db.commit()

In [1]:
cursor.execute("SELECT * FROM zigbang;")
cursor.fetchall()

SyntaxError: invalid syntax (<ipython-input-1-711ce50f6b54>, line 2)

* 월세 50이상인애들 뽑음

In [24]:
import pandas as pd

In [25]:
pd.read_sql("SELECT * FROM zigbang", db)

                                     address     phonenumber  deposit  rent
0              서울특별시 구로구 가마산로 286 101호 (구로동)  0507-1280-2016     5500     0
1                             충남 당진시 읍내동 985   010-2910-4300     2000    50
2                                        nan   010-4705-6713      300    30
3                        서울특별시 구로구 구로동 97-17     02-864-6666     1000    45
4    경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858     2000    35
5                      부산광역시 부산진구 전포동 309-50  0507-1280-8473      300    26
6                        서울특별시 구로구 구로동 97-17     02-864-6666    10000     0
7                                        nan   010-9327-2443      500    35
8                   서울특별시 관악구 봉천동 1611-23 1층  0507-1280-1758      200    41
9    경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      300    55
10                       서울특별시 성동구 도선동 285-1    02-2295-2295     8000     0
11                     부산시 부산진구 전포동 661-1 1층   010-5050-3777    11000     0
12                  서울특별시 관악구 봉천동 1611-23 1층  0507-1280-1758      100    37
13         서울특별시 종로구 숭인동 201-11 유케이오피스텔 101호  0507-1280-6783     6000     0
14   경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858     1000    50
15                       서울특별시 강남구 봉은사로33길14   010-4734-5665     1000   130
16           서울특별시 성북구 동소문로 23길 34 (동선동5가38)  0507-1280-0913     5000    50
17                         서울특별시 광진구 능동로 147   010-8503-7100     7500     0
18   경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      500    50
19               경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      200    27
20  경기도 부천시 원미구 상3동 531-3번지 광장프라자 106호 광장부동산   010-9169-9399     2000    25
21                            충남 당진시 읍내동 985   010-2910-4300      300    28
22                   서울특별시 동대문구 이문로 40 (휘경동)  0507-1280-1411      500    40
23            서울특별시 광진구 아차산로 25길 7, 1층 (화양동)  0507-1280-4998     1000    45
24               서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     2000    70
25               서울 강남구 강남대로84길 15, 111(역삼동)   010-3757-9850     1000    85
26            서울특별시 마포구 노고산동 31-157번지 에버빌딩2층  0507-1280-1672     8000     0
27               서울특별시 구로구 구로동 103-11 한솔로이젠트   010-2482-5292     3000    40
28                서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305     5000    33
29   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
..                                       ...             ...      ...   ...
43                서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305      500    55
44                      서울특별시 중랑구 면목동 105-29  0507-1280-8071      500    40
45                         서울시 강남구 삼성로63길 15   010-4187-0222     1000    50
46            서울특별시 관악구 봉천동 875-1 관악캠퍼스타워 1층  0507-1280-7645     5000    10
47                  서울특별시 관악구 봉천동 1611-23 1층  0507-1280-1758      100    39
48               경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      200    27
49              서울특별시 강남구 테헤란로22길 72 1층(역삼동)  0507-1280-4100     6000    30
50                     서울특별시 강서구 화곡동 342-100  0507-1280-5503     4000     0
51                       서울특별시 관악구 봉천동1665-7  0507-1280-8679    14000     0
52                     부산시 부산진구 전포동 661-1 1층   010-5050-3777     7500     0
53            서울특별시 마포구 월드컵로36길14두산위브센티움412호  0507-1280-3984     2000    80
54                  서울특별시 관악구 봉천동 1611-23 1층  0507-1280-0478     1000    35
55                     부산광역시 부산진구 전포동 309-50  0507-1280-7705    18000     0
56               서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     5000   105
57                       서울특별시 중랑구 묵동 177-28  0507-1280-6032    13000     0
58                      서울특별시 중랑구 면목동 105-29  0507-1280-8071      500    45
59                    서울특별시 관악구 남부순환로230길 12  0108-2216-8421      100    44
60               경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      500    55
61   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265      100    90
62                                       nan   010-4667-7617     7500     0
63              서울특별시 강남구 봉은사로61길 30 1층(삼성동)   010-4019-0430     1000    70
64                      서울특별시 중랑구 면목동 105-29  0507-1280-8071      500    40
65                    서울특별시 관악구 남부순환로230길 12  0108-2216-8421      100    34
66                                화곡동 343-57   010-5180-1559       60    55
67       부산시 수영구 광안3동 1069-3 동일아파트상가 108-102   010-3922-4689      500    33
68   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
69                    서울특별시 관악구 남부순환로230길 12  0108-2216-8421      300    40
70        경기도 안양시 만안구 안양2동 815-7 한양하이츠빌 102호  0507-1280-8080     1000    45
71                     서울특별시 강남구 역삼동 672-2번지  0507-1280-1797      100   100
72                            충남 당진시 읍내동 985   010-2910-4300      700    43

[73 rows x 4 columns]

* db쿼리로 불러오기

In [26]:
pd.read_sql("SELECT * FROM zigbang WHERE rent > 50", db)

                                    address     phonenumber  deposit  rent
0   경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      300    55
1                       서울특별시 강남구 봉은사로33길14   010-4734-5665     1000   130
2               서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     2000    70
3               서울 강남구 강남대로84길 15, 111(역삼동)   010-3757-9850     1000    85
4   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
5               서울특별시 구로구 구로동 103-11 한솔로이젠트   010-2482-5292     1000    70
6                 서울특별시 은평구 통일로69길 33 (대조동)  0507-1280-2193     2000    60
7   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265     1000    90
8                 서울특별시 은평구 통일로69길 33 (대조동)  0507-1280-2193     2000    60
9                서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305      500    55
10           서울특별시 마포구 월드컵로36길14두산위브센티움412호  0507-1280-3984     2000    80
11              서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     5000   105
12              경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      500    55
13  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265      100    90
14             서울특별시 강남구 봉은사로61길 30 1층(삼성동)   010-4019-0430     1000    70
15                               화곡동 343-57   010-5180-1559       60    55
16  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
17                    서울특별시 강남구 역삼동 672-2번지  0507-1280-1797      100   100

In [27]:
pd.read_sql("SELECT * FROM zigbang WHERE rent > 50 AND deposit < 1000 ORDER BY address", db)

                                   address     phonenumber  deposit  rent
0  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
1  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265      100    90
2  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
3  경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      300    55
4              경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      500    55
5                    서울특별시 강남구 역삼동 672-2번지  0507-1280-1797      100   100
6               서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305      500    55
7                               화곡동 343-57   010-5180-1559       60    55

* pandas로 50이상 뽑기

In [28]:
df = pd.read_sql("SELECT * FROM zigbang;", db)
df

                                     address     phonenumber  deposit  rent
0              서울특별시 구로구 가마산로 286 101호 (구로동)  0507-1280-2016     5500     0
1                             충남 당진시 읍내동 985   010-2910-4300     2000    50
2                                        nan   010-4705-6713      300    30
3                        서울특별시 구로구 구로동 97-17     02-864-6666     1000    45
4    경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858     2000    35
5                      부산광역시 부산진구 전포동 309-50  0507-1280-8473      300    26
6                        서울특별시 구로구 구로동 97-17     02-864-6666    10000     0
7                                        nan   010-9327-2443      500    35
8                   서울특별시 관악구 봉천동 1611-23 1층  0507-1280-1758      200    41
9    경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      300    55
10                       서울특별시 성동구 도선동 285-1    02-2295-2295     8000     0
11                     부산시 부산진구 전포동 661-1 1층   010-5050-3777    11000     0
12                  서울특별시 관악구 봉천동 1611-23 1층  0507-1280-1758      100    37
13         서울특별시 종로구 숭인동 201-11 유케이오피스텔 101호  0507-1280-6783     6000     0
14   경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858     1000    50
15                       서울특별시 강남구 봉은사로33길14   010-4734-5665     1000   130
16           서울특별시 성북구 동소문로 23길 34 (동선동5가38)  0507-1280-0913     5000    50
17                         서울특별시 광진구 능동로 147   010-8503-7100     7500     0
18   경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      500    50
19               경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      200    27
20  경기도 부천시 원미구 상3동 531-3번지 광장프라자 106호 광장부동산   010-9169-9399     2000    25
21                            충남 당진시 읍내동 985   010-2910-4300      300    28
22                   서울특별시 동대문구 이문로 40 (휘경동)  0507-1280-1411      500    40
23            서울특별시 광진구 아차산로 25길 7, 1층 (화양동)  0507-1280-4998     1000    45
24               서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     2000    70
25               서울 강남구 강남대로84길 15, 111(역삼동)   010-3757-9850     1000    85
26            서울특별시 마포구 노고산동 31-157번지 에버빌딩2층  0507-1280-1672     8000     0
27               서울특별시 구로구 구로동 103-11 한솔로이젠트   010-2482-5292     3000    40
28                서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305     5000    33
29   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
..                                       ...             ...      ...   ...
43                서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305      500    55
44                      서울특별시 중랑구 면목동 105-29  0507-1280-8071      500    40
45                         서울시 강남구 삼성로63길 15   010-4187-0222     1000    50
46            서울특별시 관악구 봉천동 875-1 관악캠퍼스타워 1층  0507-1280-7645     5000    10
47                  서울특별시 관악구 봉천동 1611-23 1층  0507-1280-1758      100    39
48               경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      200    27
49              서울특별시 강남구 테헤란로22길 72 1층(역삼동)  0507-1280-4100     6000    30
50                     서울특별시 강서구 화곡동 342-100  0507-1280-5503     4000     0
51                       서울특별시 관악구 봉천동1665-7  0507-1280-8679    14000     0
52                     부산시 부산진구 전포동 661-1 1층   010-5050-3777     7500     0
53            서울특별시 마포구 월드컵로36길14두산위브센티움412호  0507-1280-3984     2000    80
54                  서울특별시 관악구 봉천동 1611-23 1층  0507-1280-0478     1000    35
55                     부산광역시 부산진구 전포동 309-50  0507-1280-7705    18000     0
56               서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     5000   105
57                       서울특별시 중랑구 묵동 177-28  0507-1280-6032    13000     0
58                      서울특별시 중랑구 면목동 105-29  0507-1280-8071      500    45
59                    서울특별시 관악구 남부순환로230길 12  0108-2216-8421      100    44
60               경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      500    55
61   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265      100    90
62                                       nan   010-4667-7617     7500     0
63              서울특별시 강남구 봉은사로61길 30 1층(삼성동)   010-4019-0430     1000    70
64                      서울특별시 중랑구 면목동 105-29  0507-1280-8071      500    40
65                    서울특별시 관악구 남부순환로230길 12  0108-2216-8421      100    34
66                                화곡동 343-57   010-5180-1559       60    55
67       부산시 수영구 광안3동 1069-3 동일아파트상가 108-102   010-3922-4689      500    33
68   경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
69                    서울특별시 관악구 남부순환로230길 12  0108-2216-8421      300    40
70        경기도 안양시 만안구 안양2동 815-7 한양하이츠빌 102호  0507-1280-8080     1000    45
71                     서울특별시 강남구 역삼동 672-2번지  0507-1280-1797      100   100
72                            충남 당진시 읍내동 985   010-2910-4300      700    43

[73 rows x 4 columns]

In [37]:
df.rent > 50

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24     True
25     True
26    False
27    False
28    False
29     True
      ...
43     True
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53     True
54    False
55    False
56     True
57    False
58    False
59    False
60     True
61     True
62    False
63     True
64    False
65    False
66     True
67    False
68     True
69    False
70    False
71     True
72    False
Name: rent, dtype: bool

In [41]:
df["rent"]>50

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15     True
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24     True
25     True
26    False
27    False
28    False
29     True
      ...
43     True
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
52    False
53     True
54    False
55    False
56     True
57    False
58    False
59    False
60     True
61     True
62    False
63     True
64    False
65    False
66     True
67    False
68     True
69    False
70    False
71     True
72    False
Name: rent, dtype: bool

In [42]:
# df.rent 부울리언 시리즈와 행렬곱
df[df["rent"] > 50]

                                    address     phonenumber  deposit  rent
9   경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      300    55
15                      서울특별시 강남구 봉은사로33길14   010-4734-5665     1000   130
24              서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     2000    70
25              서울 강남구 강남대로84길 15, 111(역삼동)   010-3757-9850     1000    85
29  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
34              서울특별시 구로구 구로동 103-11 한솔로이젠트   010-2482-5292     1000    70
35                서울특별시 은평구 통일로69길 33 (대조동)  0507-1280-2193     2000    60
37  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265     1000    90
39                서울특별시 은평구 통일로69길 33 (대조동)  0507-1280-2193     2000    60
43               서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305      500    55
53           서울특별시 마포구 월드컵로36길14두산위브센티움412호  0507-1280-3984     2000    80
56              서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     5000   105
60              경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      500    55
61  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265      100    90
63             서울특별시 강남구 봉은사로61길 30 1층(삼성동)   010-4019-0430     1000    70
66                               화곡동 343-57   010-5180-1559       60    55
68  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
71                    서울특별시 강남구 역삼동 672-2번지  0507-1280-1797      100   100

In [43]:
df[df.rent > 50]

                                    address     phonenumber  deposit  rent
9   경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      300    55
15                      서울특별시 강남구 봉은사로33길14   010-4734-5665     1000   130
24              서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     2000    70
25              서울 강남구 강남대로84길 15, 111(역삼동)   010-3757-9850     1000    85
29  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
34              서울특별시 구로구 구로동 103-11 한솔로이젠트   010-2482-5292     1000    70
35                서울특별시 은평구 통일로69길 33 (대조동)  0507-1280-2193     2000    60
37  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265     1000    90
39                서울특별시 은평구 통일로69길 33 (대조동)  0507-1280-2193     2000    60
43               서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305      500    55
53           서울특별시 마포구 월드컵로36길14두산위브센티움412호  0507-1280-3984     2000    80
56              서울특별시 강남구 논현로76길 14 1층(역삼동)  0507-1280-3843     5000   105
60              경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      500    55
61  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265      100    90
63             서울특별시 강남구 봉은사로61길 30 1층(삼성동)   010-4019-0430     1000    70
66                               화곡동 343-57   010-5180-1559       60    55
68  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
71                    서울특별시 강남구 역삼동 672-2번지  0507-1280-1797      100   100

In [44]:
where_rent = df["rent"] > 50
where_deposit = df["deposit"] < 1000
# 각각은 시리즈임

In [54]:
df[where_rent][where_deposit].sort_values('address')

/home/ubuntu/.pyenv/versions/3.5.1/envs/play/lib/python3.5/site-packages/pandas/core/frame.py:1997: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  "DataFrame index.", UserWarning)

                                    address     phonenumber  deposit  rent
29  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
61  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265      100    90
68  경기도 고양시 일산동구 백석동 1318-4 일산비잔티움 2단지 103호   010-9790-4265       60    60
9   경기도 부천시 원미구 중동 1145-1 메트로팰리스 2차 B동 106호  0507-1280-0858      300    55
60              경북 구미시 형곡동 168-4번지 대림베스트빌2차  0000-0000-0000      500    55
71                    서울특별시 강남구 역삼동 672-2번지  0507-1280-1797      100   100
43               서울특별시 마포구 도화동 4-48(새창로 34)  0507-1280-7305      500    55
66                               화곡동 343-57   010-5180-1559       60    55

## apply 사용

In [46]:
df[df.deposit > 10000]

                  address     phonenumber  deposit  rent
11  부산시 부산진구 전포동 661-1 1층   010-5050-3777    11000     0
38    서울특별시 광진구 자양로13길 60  0507-1280-5505    11000     0
51    서울특별시 관악구 봉천동1665-7  0507-1280-8679    14000     0
55  부산광역시 부산진구 전포동 309-50  0507-1280-7705    18000     0
57    서울특별시 중랑구 묵동 177-28  0507-1280-6032    13000     0

In [47]:
df.address.apply(lambda x: if

SyntaxError: invalid syntax (<ipython-input-47-02ed3557c747>, line 1)

In [49]:
def apple(x):
    if x > 10000:
        return 10000

In [50]:
df.deposit.apply(apple)

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       NaN
6       NaN
7       NaN
8       NaN
9       NaN
10      NaN
11    10000
12      NaN
13      NaN
14      NaN
15      NaN
16      NaN
17      NaN
18      NaN
19      NaN
20      NaN
21      NaN
22      NaN
23      NaN
24      NaN
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
      ...
43      NaN
44      NaN
45      NaN
46      NaN
47      NaN
48      NaN
49      NaN
50      NaN
51    10000
52      NaN
53      NaN
54      NaN
55    10000
56      NaN
57    10000
58      NaN
59      NaN
60      NaN
61      NaN
62      NaN
63      NaN
64      NaN
65      NaN
66      NaN
67      NaN
68      NaN
69      NaN
70      NaN
71      NaN
72      NaN
Name: deposit, dtype: float64

In [53]:
df[df.deposit > 10000]

                  address     phonenumber  deposit  rent
11  부산시 부산진구 전포동 661-1 1층   010-5050-3777    11000     0
38    서울특별시 광진구 자양로13길 60  0507-1280-5505    11000     0
51    서울특별시 관악구 봉천동1665-7  0507-1280-8679    14000     0
55  부산광역시 부산진구 전포동 309-50  0507-1280-7705    18000     0
57    서울특별시 중랑구 묵동 177-28  0507-1280-6032    13000     0